### ISSUE TITLE
Reduce memory footprint for large datasets

### ISSUE THREAD

**Issue by a-slide** [a-slide/pycoMeth#14]
At the moment pycoMeth CpG aggregate uses a lot of memory to reorder CpG positions from the unsorted reads generated by Nanopolish call-methylation. This can become a bottleneck for big Promethion datasets.

In an early prototype I indexed the Nanopolish output file by coordinates but retrieving the data afterwards was highly IO intensive and hence super slow

A solution would be to split the data per chromosome or per fixed size genomic interval using temporary files on disk. Then process each files iteratively or in parallel.

**Comment by a-slide** [comment]
Ideas to do that:
- Split per chromosome on disk
- Use Dask arrays (probably the best option but add an extra dependency)

**Comment by rrazaghi** [comment]
beautiful package adrien! Dask is a great idea and I have played with it but it's not very robust yet and predict the dependency will cause issues. I think splitting and making a database per contig similar to nanocompore will be good. I did try sorting and using tabix for a bit but if there are fluctuations in coverage in large datasets, tabix stalls.

**Comment by a-slide** [comment]
Thanks for your feedback Roham.
I might still give a try to Dask, because I find it very elegant, but on the other hand I am reluctant to add too many dependencies and there are already more than I like :)
