### ISSUE TITLE
ValueError: Precision not allowed in integer format specifier

### ISSUE THREAD

**Issue by hasindu2008** [a-slide/pycoMeth#15]
Thank you very much for writing this robust piece of software. I was amazed that this python-based tool installed without any dependency issues when directly installed using pip - which is rare for a python based tool. I managed to run the CpG_Aggregate  command successfully but in the Meth_Comp  command, I came across an issue.

I first used the following command to generate the frequency count 
`pycoMeth  CpG_Aggregate  -i input -f hg38noAlt.fa -t name.tsv -b name.bed --progress`
After doing that for 6 different datasets I called 
`pycoMeth   Meth_Comp -i name1.tsv name2.tsv name3.tsv ......  -f hg38noAlt.fa -t compared.tsv -b compared.bed`
after a while this returned the following:
```
## Checking options and input files ##
## Parsing files ##
        Reading input files header and checking consistancy between headers
        Starting asynchronous file parsing
        Adjust pvalues
        Writing output file
/home/hasindu/.local/lib/python3.6/site-packages/pycoMeth/Meth_Comp.py:370: RuntimeWarning: divide by zero encountered in log10
  score = -np.log10(res.adj_pvalue)
        Results summary
                Sites with insufficient samples: 4,039,149
                Sites with insufficient effect size: 15,418,712
                Valid sites: 3,685,388
                Sites with significant pvalue (< 0.01): 3,655,192
                Sites with significant FDR adj pvalue (< 0.01): 3,654,900
Traceback (most recent call last):
  File "/home/hasindu/.local/bin/pycoMeth", line 11, in <module>
    sys.exit(main())
  File "/home/hasindu/.local/lib/python3.6/site-packages/pycoMeth/__main__.py", line 96, in main
    args.func(**vars(args))
  File "/home/hasindu/.local/lib/python3.6/site-packages/pycoMeth/Meth_Comp.py", line 193, in Meth_Comp
    writer.write (res)
  File "/home/hasindu/.local/lib/python3.6/site-packages/pycoMeth/Meth_Comp.py", line 342, in write
    self._write_bed (res)
  File "/home/hasindu/.local/lib/python3.6/site-packages/pycoMeth/Meth_Comp.py", line 379, in _write_bed
    res.chr_name, res.start, res.end, score, res.start, res.end, color))
ValueError: Precision not allowed in integer format specifier
```
Am I doing something wrong?

**Comment by a-slide** [comment]
Hi @hasindu2008,
I don't think you are doing anything wrong but it looks like an edge case I haven't came across.
I suspect there is a NAN value or a negative pvalue generated (for some reason), leading to a formatting error when trying to write the value in a BED file. I will push a fix ASAP.
Thanks
Ad

**Comment by a-slide** [comment]
I am not 100% sure it will work but I added a few safeguards that should prevent the error.
Could you try to update your version from the dev repository ?

`pip install --index-url https://test.pypi.org/simple/ pycoMeth -U` 

It should update to version 0.3.3. 

If this was indeed a missing pvalue error you should have additional fields in the results summary generated at the end `Sites with invalid pvalue` or `Sites with invalid adjusted pvalue`.

Please let me know either way.

Ad

**Comment by hasindu2008** [comment]
Thank you for the quick response. While using that command to install I got the following issue with numPy. 

```
pip3 install --index-url https://test.pypi.org/simple/ pycoMeth -U
Collecting pycoMeth
  Using cached https://test-files.pythonhosted.org/packages/31/be/5c505b3feb062499b0c381e7cd6c0f4b87130f8279bbf9a5b27c26f10d12/pycoMeth-0.3.3.tar.gz
Collecting numpy>=1.14.0 (from pycoMeth)
  Could not find a version that satisfies the requirement numpy>=1.14.0 (from pycoMeth) (from versions: 1.9.3)
No matching distribution found for numpy>=1.14.0 (from pycoMeth)
```

**Comment by a-slide** [comment]
Oh yes, sorry. You have to install from the main repo first, because the dependencies not available on the dev repo. 

```pip3 install pycoMeth```

and then update to the dev version

```pip3 install --index-url https://test.pypi.org/simple/ pycoMeth -U```

Hope it works

**Comment by hasindu2008** [comment]
It was not successful. However, I tried to install by manually building from the git repo's dev branch and it that worked. Now it successfully ran. Thank you very much for the quick fix.

**Comment by a-slide** [comment]
Good that it works in the end.
Could you let me know if you had counts in the `Sites with invalid pvalue` or `Sites with invalid adjusted pvalue` fields ?
I kinda guess it was because of that but I could not reproduce with any files on my side.

Oh and also did you use Nanopolish or your GPU boosted version ?

**Comment by hasindu2008** [comment]
is it in log output - the log output is
```
## Checking options and input files ##
## Parsing files ##
        Reading input files header and checking consistancy between headers
        Starting asynchronous file parsing
        Adjust pvalues
        Writing output file
/home/hasindu/realtime_meth/pycometh/pycoMeth/pycoMeth/Meth_Comp.py:371: RuntimeWarning: divide by zero encountered in log10
  score = -np.log10(res["adj_pvalue"])
        Results summary
                Sites with insufficient samples: 23,137,400
                Sites with insufficient effect size: 5,260
                Valid sites: 718
                Sites with significant pvalue: 714
                Sites with significant adjusted pvalue: 714
```
The tsv output also seem not to have a such field.
I also attach the columns: n_samples, pvalue  and the adj_pvalue from the tsv output
[out.txt](https://github.com/a-slide/pycoMeth/files/4265030/out.txt)

Well, there are datasets that some are from nanopolish and some are from the GPU accelerated version. The strand column is not present in them as in the latest nanopolish - will that cause a problem?

**Comment by a-slide** [comment]
pycoQC doesn't store the strand values so It should be an issue.
I am a little worry to see that you have those 0 lines in your tsv_output file...

Did you modify the max_missing parameter by any chance ?

Thanks

**Comment by a-slide** [comment]
Ok I got it. I think the pvalues are so low that it its the lower limits of a np.float64 size.
...mmmm, It must be extremely different methylation profiles you are looking at.

Did you run the MethComp on CpG_aggregate output or Interval_ aggregate ?
If not, in terms of biological relevance ant interpretability, I would recommend to go for CpG islands aggregation

Cheers

**Comment by a-slide** [comment]
It is definitely due to these very low pvalues defaulting to 0. I now force clip pvalues to be between the minimal non-zero float value and 1. I push a new version with the fix on the dev branch (0.3.4)
This time I think they should be no exceptions or warnings raised.

You can update the same way as before

`pip install git+https://github.com/a-slide/pycoMeth.git@dev -U`

Thanks

**Comment by hasindu2008** [comment]
I used the default parameters. There were six samples on each which I ran
pycoMeth  CpG_Aggregate  -i $input -f hg38noAlt.fa -t $each.tsv -b $each.bed --progress

Then on  all, I ran 
pycoMeth Meth_Comp -i [all 6 tsv outputs] -f hg38noAlt.fa -t compared.tsv -b compared.bed

Now let me try the latest version

**Comment by hasindu2008** [comment]
The latest version did not give any warnings
``
## Checking options and input files ##
## Parsing files ##
        Reading input files header and checking consistancy between headers
        Starting asynchronous file parsing
        Adjust pvalues
        Writing output file
        Results summary
                Sites with insufficient samples: 23,137,400
                Sites with insufficient effect size: 5,260
                Valid sites: 718
                Sites with significant pvalue: 714
                Sites with significant adjusted pvalue: 714
                Sites with non-significant pvalue: 4
                Sites with non-significant adjusted pvalue: 4
````

**Comment by a-slide** [comment]
Perfect. Glad to see it working
Thanks for your help
