### ISSUE TITLE
division by zero in CGI_Finder

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [a-slide/pycoMeth#20]
Hi,

There seems to be an issue in the CGI_Finder class with division by zero. I have not looked into it yet. Might get to this later. Putting it here for tracking.

~/anaconda3/envs/pycoMeth/lib/python3.6/site-packages/pycoMeth/CGI_Finder.py in CGI_Finder(ref_fasta_fn, output_tsv_fn, output_bed_fn, merge_gap, min_win_len, min_CG_freq, min_obs_CG_ratio, verbose, quiet, progress, **kwargs)
    142                             if previous_valid:
    143                                 counter["Valid merged windows"]+=1
--> 144                                 win_len, win_cg_count, win_cg_freq, win_obs_exp = compute_win (seq[valid_win_start:valid_win_end])
    145                                 writer.write(seq_name, valid_win_start, valid_win_end, win_len, win_cg_count, win_cg_freq, win_obs_exp)
    146 

~/anaconda3/envs/pycoMeth/lib/python3.6/site-packages/pycoMeth/CGI_Finder.py in compute_win(win_seq)
    238 
    239     cg_freq = (c_count+g_count)/win_len
--> 240     obs_exp = cg_count/(c_count*g_count/win_len)
    241 
    242     return (win_len, cg_count, cg_freq, obs_exp)

ZeroDivisionError: float division by zero

**Comment by a-slide** [comment]
Hi @BenjaminSchwessinger 

Looks like an AT rich region with no C or G in it.
I will add a fix for that in the next release. 
In the meantime you can use an externally provided Bed file containing CpG Islands coordinates
Thanks for spotting it

Cheers

Ad

**Comment by a-slide** [comment]
Fixed in version 0.4+
