### ISSUE TITLE
What CpG modification is support in pycoMeth

### ISSUE THREAD

**Issue by PanZiwei** [a-slide/pycoMeth#28]
Hi,
What CpG modification is support in pycoMeth? Only 5mC from 5mC? How about 5hmC/5fC/5caC?  How about 4mC?

Also, any other modification such as 4mA?

**Comment by a-slide** [comment]
Hi @PanZiwei,
pycoMeth works downstream to Nanopolish and at the moment the only CpG modification supported is 5mC. I might add support for Megalodon at some point (which detects both m5C and 5hmC) but not in a near future.
