### ISSUE TITLE
Add support for Megalodon and DeepSignal

### ISSUE THREAD

**Issue by a-slide** [a-slide/pycoMeth#29]

**Comment by phpeters** [comment]
Hej, thanks a lot for your great work! Just a quick question: Is this enhancement for megalodon planned to be implemented soonish? Thanks again and best regards!
Philipp

**Comment by a-slide** [comment]
Hi @phpeters 
pycoMeth is going through a major revamp at the moment. We might consider including support for megalodon.
Would you be able to provide example files so we can have a look at how to implement it ? 
Thanks

**Comment by phpeters** [comment]
Hej, 
thanks for your quick reply! I made a small test run on a lambda phage, this is the output megalodon provides (without the variant calling part):
https://ngs.vbcf.ac.at/filemanager/byurl/tLQnl0ZLII-testset.tgz 
Is this what you need, or is there some more? Thanks and best!
Philipp

**Comment by alkputman** [comment]
Hello,
Are you planning on adding support for deepsignal2?
Thanks.
