### ISSUE TITLE
`ERROR: Not all the chromosomes found in the data file are present in the GFF3 file.` but this is incorrect

### ISSUE THREAD

**Issue by jolespin** [a-slide/pycoMeth#37]
I'm running an analysis using [Rattus_norvegicus from Ensembl](https://useast.ensembl.org/Rattus_norvegicus/Info/Index).  I'm using both the GFF3 and genome fasta files that have been unmodified. 

I'm receiving the following error:
`ERROR: Not all the chromosomes found in the data file are present in the GFF3 file. This will lead to missing transcript ids`

I double checked and all of the sequence records in GFF3 are accounted for in the genome file and vice versa.  In particular, I'm using:

```
Rattus_norvegicus.Rnor_6.0.dna_rm.toplevel.fa
Rattus_norvegicus.Rnor_6.0.99.gff3
```

**Comment by a-slide** [comment]
Hi @jolespin,

Sorry for the delay
It is not comparing the genome and gff3 files but the data from the pycoMeth MethComp file with the gff3.
Did you check if all the ids are matching between those 3 files ?
Anyway it is just a warning and it should not affect really your results if all the main references are there.
Best

**Comment by a-slide** [comment]
Hi Josh,

For the record, did you manage to solve the issue ?

**Comment by jolespin** [comment]
I hadn't looked into it since you mentioned that the warnings shouldn't affect the results.  I just wanted to log everything in case i was useful for you.
