### ISSUE TITLE
Is it possible to use `Comp_Report` without a gff3 file? 

### ISSUE THREAD

**Issue by jolespin** [a-slide/pycoMeth#38]
I'm working on a project where we are not considering annotations.  There are also no gene models for our organism so we have no gff3 available.  Is it possible to still use `Comp_Report` without a gff3 file to get a report of differential methylation events by intervals? 

https://adrienleger.com/pycoMeth/Comp_Report/CLI_usage/

**Comment by a-slide** [comment]
Unfortunately no, at the moment it is expecting a a GFF3 file and in my opinion it is 90% of the interest of the report. Now, you are right it could be an interesting option to still get the 10% left for non-annotated organisms. I will keep that open as a feature request but I am not going to be able to implement that in the next 3 or 4 weeks.
I will be happy to take a Pull Request if you want to try implementing it. 
A quick and dirty alternative (although I am not 100% sure it will work) would be to use a decoy GFF file from yeast for example or maybe an empty file.
