### ISSUE TITLE
Invalid Input file type

### ISSUE THREAD

**Issue by brookshenry3** [a-slide/pycoMeth#40]
Hi there, I'm trying to use PycoMeth with the output of [f5c's](https://hasindu2008.github.io/f5c/docs/overview) call methylation function which should be the exact same format as nanopolish's, however when I try to run PycoMeth CpG_Aggregate I get the following error:

```
Cannot import dependencies required for static image export
## Checking options and input files ##
## Parsing methylation_calls file ##
Traceback (most recent call last):
  File "/home/k001y/.conda/envs/snakemake/bin/pycoMeth", line 10, in <module>
    sys.exit(main())
  File "/home/k001y/.conda/envs/snakemake/lib/python3.6/site-packages/pycoMeth/__main__.py", line 116, in main
    args.func(**vars(args))
  File "/home/k001y/.conda/envs/snakemake/lib/python3.6/site-packages/pycoMeth/CpG_Aggregate.py", line 69, in CpG_Aggregate
    raise pycoMethError("Invalid input file type passed (nanopolish_fn). Expecting Nanopolish call_methylation output TSV file")
pycoMeth.common.pycoMethError: Invalid input file type passed (nanopolish_fn). Expecting Nanopolish call_methylation output TSV file
```

Here's the format of the TSV file I'm using:

chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence

Thanks in advance for any help/advice!

**Comment by brookshenry3** [comment]
Changing the header of the input TSV to the format suggested in Issue #33 did not seem to change the error either.

**Comment by a-slide** [comment]
Hi @brookshenry3 
Pycometh is expecting exactly the following fields in the nanopolish file:
`"chromosome", "strand", "start", "end" , "read_name", "log_lik_ratio", "log_lik_methylated", "log_lik_unmethylated"`
I cannot see the strand field in the header you provided.

**Comment by brookshenry3** [comment]
After adding the strand field and getting rid of the extra fields (num_calling_strands, num_cpgs sequence) it's working now!

**Comment by a-slide** [comment]
What does the f5c header look like ?

**Comment by brookshenry3** [comment]
```
chromosome	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated	num_calling_strands	num_cpgs	sequence
NC_000001.11	32587	32587	4f1fe68a-7e73-4f22-a689-a504452e68d7	13.78	-248.35	-262.14	1	1	GTGCACGCAAA
NC_000001.11	32645	32645	4f1fe68a-7e73-4f22-a689-a504452e68d7	18.85	-280.01	-298.86	1	1	CCCATCGGTGA

```

**Comment by a-slide** [comment]
`num_calling_strands` and `num_cpgs` and `sequence` are not needed.

I could actually remove `strand` because the strandness is not even used. I will re-open the issue to fix it later

**Comment by a-slide** [comment]
This version is deprecated see [Rene Snajder](https://github.com/snajder-r) fork at the following URL https://github.com/snajder-r/pycoMeth
