### ISSUE TITLE
Use two-sided alternative in mannwhitneyu test

### ISSUE THREAD

**Issue by snajder-r** [a-slide/pycoMeth#42]
Regarding the mannwhitneyu test in the differential methylation calling:

https://github.com/a-slide/pycoMeth/blob/e11e705e8fdff0514aaf50d8cf716741d270bd62/pycoMeth/Meth_Comp.py#L310

Here, scipy.stats.mannwhitneyu is called with the default parameters. The `alternative` parameter defaults to `None`. According to the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html):

> None: computes p-value half the size of the ‘two-sided’ p-value and a different U statistic. The default behavior is not the same as using ‘less’ or ‘greater’; it only exists for backward compatibility and is deprecated.

This should be changed to the following to get proper p-values for two-sided tests:

`statistics, pvalue = mannwhitneyu(raw_llr_list[0], raw_llr_list[1], alternative='two-sided') `

**Comment by a-slide** [comment]
fixed
