### ISSUE TITLE
No valid sites left after coverage filtering

### ISSUE THREAD

**Issue by brookshenry3** [a-slide/pycoMeth#43]
Hey there,

Trying to run pycoMeth `CpG_Aggregate` on a sample however I get the following error:

```
## Checking options and input files ##
	[DEBUG]: Options summary
	[DEBUG]: 	Package name: pycoMeth
	[DEBUG]: 	Package version: 0.4.7
	[DEBUG]: 	Timestamp: 2020-09-11 16:24:24.427901
	[DEBUG]: 	kwargs
	[DEBUG]: 		subcommands: CpG_Aggregate
	[DEBUG]: 		func: <function CpG_Aggregate at 0x2af0b8fae488>
	[DEBUG]: 	progress: False
	[DEBUG]: 	quiet: False
	[DEBUG]: 	verbose: True
	[DEBUG]: 	min_llr: 2
	[DEBUG]: 	sample_id: 
	[DEBUG]: 	min_depth: 1
	[DEBUG]: 	output_tsv_fn: TEST.tsv
	[DEBUG]: 	output_bed_fn: TEST.bed
	[DEBUG]: 	ref_fasta_fn: /icgc/dkfzlsdf/analysis/C010/brooks/meth_calling_pipeline/GCF_000001405.26_GRCh38_genomic.fna
	[DEBUG]: 	nanopolish_fn: ['CLEAN_normal_chroms_meth_calls.tsv']
## Parsing methylation_calls file ##
	[DEBUG]: Opening file CLEAN_normal_chroms_meth_calls.tsv in normal mode
	[DEBUG]: Reading header from file: CLEAN_normal_chroms_meth_calls.tsv
	[DEBUG]: Column names from header: 'chromosome / strand / start / end / read_name / log_lik_ratio / log_lik_methylated / log_lik_unmethylated'
	[DEBUG]: Input file type: call_methylation
	Starting to parse file Nanopolish methylation call file
	[DEBUG]: Starting to parse file CLEAN_normal_chroms_meth_calls.tsv
	[DEBUG]: End of file: CLEAN_normal_chroms_meth_calls.tsv
	[DEBUG]: All files done
	Parsing summary
		Lines Parsed: 9,599,265
		Line successfully parsed: 9,599,265
		Input files: 1
	Filtering out low coverage sites
	[DEBUG]: Closing file:CLEAN_normal_chroms_meth_calls.tsv
Traceback (most recent call last):
  File "/home/k001y/.conda/envs/pycometh/bin/pycoMeth", line 10, in <module>
    sys.exit(main())
  File "/home/k001y/.conda/envs/pycometh/lib/python3.6/site-packages/pycoMeth/__main__.py", line 114, in main
    args.func(**vars(args))
  File "/home/k001y/.conda/envs/pycometh/lib/python3.6/site-packages/pycoMeth/CpG_Aggregate.py", line 81, in CpG_Aggregate
    sites_index.filter_low_count(min_depth)
  File "/home/k001y/.conda/envs/pycometh/lib/python3.6/site-packages/pycoMeth/CpG_Aggregate.py", line 167, in filter_low_count
    raise pycoMethError ("No valid sites left after coverage filtering")
pycoMeth.common.pycoMethError: No valid sites left after coverage filtering
```

This happens even when the `--min_depth` flag is set to 1. I'm wondering if it maybe has something to do with a discrepancy between my reference genome and the input tsv file. My input file is formatted like this: 

```
chromosome	strand	start	end	read_name	log_lik_ratio	log_lik_methylated	log_lik_unmethylated
chr1	+	32587	32587	4f1fe68a-7e73-4f22-a689-a504452e68d7	13.78	-248.35	-262.14
chr1	+	32645	32645	4f1fe68a-7e73-4f22-a689-a504452e68d7	18.85	-280.01	-298.86
chr1	+	55298	55298	5f696894-1f6c-4508-871d-ef7474eca1f7	-0.13	-294.58	-294.45
```
However my reference fasta uses this style of chromosome naming convention: "NC_000001.11, NC_000002.12, etc..."

Could this be the issue? When I try to use a reference fasta that uses the "normal" chromosome names (i.e. chr1, chr2, etc.) I get a different error:

```
AttributeError: 'lt' object has no attribute 'sequence'
```

So I am not quite sure what is going wrong. Any tips/suggestions would be much appreciated! If you want me to provide additional info I'm happy to do so!

Thanks in advance!

**Comment by AGalanis97** [comment]
I was having the same issue today (running for the first time)
your input file is missing a column with the sequence. The input file must contain the following headers:
`chromosome      strand  start   end     read_name       log_lik_ratio   log_lik_methylated      log_lik_unmethylated    num_motifs      sequence`

nanopolish or f5c (i dont know what you are using) output num_cpgs which you will need to rename as num_motifs. For me what worked is to grab (and add) the necessary columns from the f5c output.

**Comment by brookshenry3** [comment]
> I was having the same issue today (running for the first time)
> your input file is missing a column with the sequence. The input file must contain the following headers:
> `chromosome strand start end read_name log_lik_ratio log_lik_methylated log_lik_unmethylated num_motifs sequence`
> 
> nanopolish or f5c (i dont know what you are using) output num_cpgs which you will need to rename as num_motifs. For me what worked is to grab (and add) the necessary columns from the f5c output.

Awesome, thanks for the help!
