### ISSUE TITLE
Missing submodule CpG_Aggregate

### ISSUE THREAD

**Issue by DrownedMala** [a-slide/pycoMeth#51]
Hello,
I'm opening this issue because I was trying to use pycoMeth to visualize nanopolish's methylation analysis output, following the guidelines provided [here](https://a-slide.github.io/pycoMeth/), but I could not find the aforementioned submodule when launching pycoMeth.
We installed pycoMeth with  `conda install -c snajder-r pycometh`, as suggested [here ](https://anaconda.org/snajder-r/pycometh).

This is the output of `pycoMeth -h`:
```
Cannot import dependencies required for static image export
usage: pycoMeth [-h] [--version]
                {Meth_Comp,Comp_Report,CGI_Finder,Meth_Seg} ...

Differential methylation calling suite for Nanopore methylation calls PycoMeth

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit

subcommands:
  pycoMeth implements the following subcommands

  {Meth_Comp,Comp_Report,CGI_Finder,Meth_Seg}
```
Is it normal for that particular submodule to be missing?

Also, what is the meaning of the line `Cannot import dependencies required for static image export`?

Thanks a lot in advance for any reply,
Have a good day,
Simone.

**Comment by DrownedMala** [comment]
So, I found [this installation](https://a-slide.github.io/pycoMeth/installation/) procedure too, which seems to be the proper one, with CpG_Aggregate.

**Comment by a-slide** [comment]
This version is deprecated see [Rene Snajder](https://github.com/snajder-r) fork at the following URL https://github.com/snajder-r/pycoMeth
