### ISSUE TITLE
pycoMeth Nextflow pipeline

### ISSUE THREAD

**Issue by MaestSi** [a-slide/pycoMeth#52]
Dear all,
I just created a Nextflow pipeline integrating minimap2 + nanopolish call-methylation + pycoMeth v0.4.25. If you want, you can check it out [here](https://github.com/MaestSi/pycoMethFlow)!
Best,
Simone

**Comment by a-slide** [comment]
Thank you, this looks neat.

**Comment by a-slide** [comment]
Would you be able to use [Rene Snajder](https://github.com/snajder-r) fork at https://github.com/snajder-r/pycoMeth as my original version is deprecated.
